// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl_djvRrEWbv5pRPD_ZTj1qoa_wGE-dQs',
    appId: '1:806942347625:web:24c2060e480eb8f70dadf8',
    messagingSenderId: '806942347625',
    projectId: 'computing-event',
    authDomain: 'computing-event.firebaseapp.com',
    storageBucket: 'computing-event.firebasestorage.app',
    measurementId: 'G-D2EHDSJRVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtdEuzRAv-VQwG-b0Wzn75xfvDXEDi2E',
    appId: '1:806942347625:android:2380dfc0b01c50580dadf8',
    messagingSenderId: '806942347625',
    projectId: 'computing-event',
    storageBucket: 'computing-event.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu4P5sMlBWw-JjKzgS-38kMCm4BjMxA_8',
    appId: '1:806942347625:ios:6c222467fe41ce770dadf8',
    messagingSenderId: '806942347625',
    projectId: 'computing-event',
    storageBucket: 'computing-event.firebasestorage.app',
    iosBundleId: 'com.example.compuvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu4P5sMlBWw-JjKzgS-38kMCm4BjMxA_8',
    appId: '1:806942347625:ios:6c222467fe41ce770dadf8',
    messagingSenderId: '806942347625',
    projectId: 'computing-event',
    storageBucket: 'computing-event.firebasestorage.app',
    iosBundleId: 'com.example.compuvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl_djvRrEWbv5pRPD_ZTj1qoa_wGE-dQs',
    appId: '1:806942347625:web:0d66f381c3d705db0dadf8',
    messagingSenderId: '806942347625',
    projectId: 'computing-event',
    authDomain: 'computing-event.firebaseapp.com',
    storageBucket: 'computing-event.firebasestorage.app',
    measurementId: 'G-7WLGCDS5TE',
  );
}
